/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: vss_topics.h
  Source: /home/parag/VSS/VISS_DDS/vss_topics.idl
  Cyclone DDS: V0.11.0

*****************************************************************/
#ifndef DDSC_VSS_TOPICS_H_EA5DAA3108227047940CE9B4456CA283
#define DDSC_VSS_TOPICS_H_EA5DAA3108227047940CE9B4456CA283

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct SchemaRequest
{
  char path[257];
} SchemaRequest;

extern const dds_topic_descriptor_t SchemaRequest_desc;

#define SchemaRequest__alloc() \
((SchemaRequest*) dds_alloc (sizeof (SchemaRequest)));

#define SchemaRequest_free(d,o) \
dds_sample_free ((d), &SchemaRequest_desc, (o))

typedef struct SchemaResponse
{
  char json[4097];
} SchemaResponse;

extern const dds_topic_descriptor_t SchemaResponse_desc;

#define SchemaResponse__alloc() \
((SchemaResponse*) dds_alloc (sizeof (SchemaResponse)));

#define SchemaResponse_free(d,o) \
dds_sample_free ((d), &SchemaResponse_desc, (o))

typedef struct VSSData
{
  char payload[2049];
} VSSData;

extern const dds_topic_descriptor_t VSSData_desc;

#define VSSData__alloc() \
((VSSData*) dds_alloc (sizeof (VSSData)));

#define VSSData_free(d,o) \
dds_sample_free ((d), &VSSData_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_VSS_TOPICS_H_EA5DAA3108227047940CE9B4456CA283 */
